language: go
go:
 - 1.6
 - 1.7
 - 1.8
 - tip

addons:
  postgresql: "9.4"

services:
 - postgresql

install:
 - go get -t github.com/hexya-erp/hexya
 - hexya generate --empty
 - go get -t -d -v ./...

script:
 - ./run_tests.sh

env:
 - Hexya_DB_DRIVER=postgres Hexya_DB_USER=postgres Hexya_DB_PASSWORD= Hexya_DB_PREFIX=hexya
