language: go
go:
 - 1.6
 - 1.7
 - 1.8
 - tip

addons:
  postgresql: "9.4"

services:
 - postgresql

install:
 - go get -t github.com/npiganeau/yep
 - yep generate --empty
 - go get -t -d -v ./...

script:
 - ./run_tests.sh

env:
 - YEP_DB_DRIVER=postgres YEP_DB_USER=postgres YEP_DB_PASSWORD= YEP_DB_PREFIX=yep
